export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOAD_POSTS = "LOAD_POSTS";
export const LOAD_POSTS_REQUEST = "LOAD_POSTS_REQUEST";
export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_POSTS_FAILURE = "LOAD_POSTS_FAILURE";

export const CREATE_POST = "CREATE_POST";
export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";

export const GET_POST = "GET_POST";
export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILURE = "GET_POST_FAILURE";

export const CHANGE_POST = "CHANGE_POST";
export const CHANGE_POST_REQUEST = "CHANGE_POST_REQUEST";
export const CHANGE_POST_SUCCESS = "CHANGE_POST_SUCCESS";
export const CHANGE_POST_FAILURE = "CHANGE_POST_FAILURE";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_CURRENT_USER_REQUEST = "GET_CURRENT_USER_REQUEST";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER_FAILURE";

export const GET_POST_COMMENTS = "GET_POST_COMMENTS";
export const GET_POST_COMMENTS_REQUESTS = "GET_POST_COMMENTS_REQUESTS";
export const GET_POST_COMMENTS_SUCCESS = "GET_POST_COMMENTS_SUCCESS";
export const GET_POST_COMMENTS_FAILURE = "GET_POST_COMMENTS_FAILURE";

export const ADD_COMMENT = "ADD_COMMENT";
export const ADD_COMMENT_REQUESTS = "ADD_COMMENT_REQUESTS";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAILURE = "ET_POST_COMMENTS_FAILURE";

export const CHANGE_COMMENT = "CHANGE_COMMENT";
export const CHANGE_COMMENT_REQUEST = "CHANGE_COMMENT_REQUEST";
export const CHANGE_COMMENT_SUCCESS = "CHANGE_COMMENT_SUCCESS";
export const CHANGE_COMMENT_FAILURE = "CHANGE_COMMENT_FAILURE";

export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE";
